### ISSUE TITLE
Error while configuring DRA818

### ISSUE THREAD

**Issue by MarcusFischerSFN** [fatpat/arduino-dra818#1]
Hi, 

I was trying your sketch but I am not able to connect to the dra818v module. While debugging I am getting the following output:

```
Starting ... 
Booting ...
initializing I/O ... done
initializing DRA818 ... DRA818: log serial connection active
DRA818::handshake
-> AT+DMOCONNECT
<- ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮ޞ⸮⸮⸮⸮⸮⸮ޞ⸮⸮⸮⸮ޞ⸮⸮⸮⸮⸮⸮ޞ⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮ޞ⸮⸮⸮⸮⸮ޞ⸮⸮⸮⸮3Returned value=0
DRA818::handshake
-> AT+DMOCONNECT
<- 3Returned value=0
DRA818::handshake
-> AT+DMOCONNECT
<- 3Returned value=0
DRA818::group
-> AT+DMOSETGROUP=0,145.5000,145.5000,0000,4,0000
<- 3Returned value=0

Error while configuring DRA818
done
Starting ... 
```

Could you help me solving that problem?

Cheers

**Comment by fatpat** [comment]
it looks like the wiring was not done correctly. but I can't really help you with this :(

**Comment by MarcusFischerSFN** [comment]
Allright, could you tell me which kind of board you used to test the code?

**Comment by fatpat** [comment]
Arduino nano

Le ven. 13 avr. 2018 à 15:14, MarcusFischerSFN <notifications@github.com> a
écrit :
