### ISSUE TITLE
Does this work with the SA818 modules?

### ISSUE THREAD

**Issue by wgaylord** [fatpat/arduino-dra818#2]
Hello, I am using the SA818 modules from NiceRF which have the same Radio chip as the DRA818 and also the same commands as the DRA818. 

I will be trying to use this library to control it and if it works I will post and update on this issue. 

I am posting this issue to see if you know ahead of time if it works or if we will both be learning something.

**Comment by fatpat** [comment]
Hi,

I have no clue if it would work with SA818. But if protocol is the same it should not be a problem.

**Comment by wgaylord** [comment]
I can confirm that this does work with the SA818 modules.
