### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by davidjmallar** [fatpat/arduino-dra818#3]
With the following setup, I am not able to build the library:
- I try to use the library from **PlatformIO** with this version: **fatpat/DRA818 @ 1.0.0**
- My other parameters:
 platform = **espressif32**
 board = **wemos_d1_mini32**
 framework = **arduino**

The issues are the following:

> .pio\libdeps\wemos_d1_mini32\DRA818\src\DRA818.cpp:190:239: error: cannot declare member function 'static DRA818* DRA818::configure(SoftwareSerial*, uint8_t, float, float, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, bool, bool, bool, Stream*)' to have static linkage [-fpermissive]

> *** [.pio\build\wemos_d1_mini32\src\main.cpp.o] Error 1
> .pio\libdeps\wemos_d1_mini32\DRA818\src\DRA818.cpp:190:239: error: default argument given for parameter 13 of 'static DRA818* DRA818::configure(SoftwareSerial*, uint8_t, float, float, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, bool, bool, bool, Stream*)' [-fpermissive]

The same 2 issues for line 190, 195 and 200

I Guess the PlatformIO Cpp compiler is more strict than the Arduino IDE's.

**Comment by fatpat** [comment]
it surely does. I can't really help you on this, sorry. Don't hesitate to PR or comment if you find a solution.

**Comment by SmittyHalibut** [comment]
See https://github.com/fatpat/arduino-dra818/pull/6  These were warnings on Arduino that I cleaned up.  THEN, I switched to PlatformIO. I didn't notice that PlatformIO wouldn't compile with these because I already fixed them.

**Comment by fatpat** [comment]
fixed in #6
