### ISSUE TITLE
Platform io registered version is broken

### ISSUE THREAD

**Issue by f4iha** [fatpat/arduino-dra818#7]
The lib available via the platformio is broken https://registry.platformio.org/libraries/fatpat/DRA818/versions. When we are trying to build we are having various message like `error: cannot declare member function to have static linkage`
The latest version of the code is however working properly, mainly due to this commit https://github.com/fatpat/arduino-dra818/commit/be92516075f7a30a9faed2914449ab94f21bfe43
Would it be possible to have a new tag generated which is using the latest version of the code and also see to update accordingly the platformio page ? 
Thanks

**Comment by fatpat** [comment]
Will do, sure

**Comment by fatpat** [comment]
v1.0.1 has been released !

**Comment by f4iha** [comment]
did you push the new version on platformIO registry ? or it is done manually ?

**Comment by fatpat** [comment]
I have no clue how it works. I don't think I registered it myself.
